name: 'rittman_analytics_assessment'
version: '1.0.0'
config-version: 2
profile: 'default'

# File paths for different dbt resources
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Where compiled SQL files are stored
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  rittman_analytics_assessment:
    marts:
      +database: sav-rittman-analytics  
      +schema: analytics
      +materialized: table

    staging:
      +database: sav-rittman-analytics
      +schema: staging
      +materialized: view 